### ISSUE TITLE
readme文件

### ISSUE THREAD

**Issue by 1zzc** [weihui1308/HotCold_Block#2]
感谢博主在红外对抗补丁方面的工作，我需要复现学习这个优秀的代码库，需要博主的详细运行步骤❀

感谢博主的帮助，我的邮箱1373983975@qq.com

**Comment by weihui1308** [comment]
感谢您对我们工作的关注。

我们会很快在这个仓库发布代码。

**Comment by 1zzc** [comment]
大概什么时候呀，我想快点上手学习


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weihui1308/HOTCOLDBlock"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 上午10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weihui1308/HOTCOLDBlock] readme文件 (Issue #2)





 
感谢您对我们工作的关注。
 
我们会很快在这个仓库发布代码。

**Comment by weihui1308** [comment]
代码已经公开，请查看仓库最新的更新

**Comment by 1zzc** [comment]
谢谢博主，项目中未发现data/custom.yaml  和data/hyps/hyp.scratch-low.yaml文件
另外FLIR数据集需要转换成什么格式❀

**Comment by weihui1308** [comment]
data/custom.yaml需要根据数据集存放路径进行编写。示例文件：victim detector/data/coco.yaml.

FLIR数据集需要转换成YOLOv5格式

**Comment by 1zzc** [comment]
缺少loss_patch 和val_patch两个文件
from loss_patch import TotalVariation, get_tvLoss
import val_patch

感谢博主的帮助❀

**Comment by weihui1308** [comment]
loss_patch.py已弃用；
val_patch.py已上传。
