### ISSUE TITLE
How to test the adversarial patch?

### ISSUE THREAD

**Issue by jeth0102** [weihui1308/HotCold_Block#4]
Hello, great work and i'm having a fun time implementing it.

main.py looks like a code to train the patch and optimize the best positions of the hotcold block.
Is there a test code available?

**Comment by wmrenr** [comment]
> Hello, great work and i'm having a fun time implementing it.
> 
> main.py looks like a code to train the patch and optimize the best positions of the hotcold block. Is there a test code available?


May I ask if you have reproduced this code? I have a question, how is the patch of the digital world of the Warming Paste and Cooling Paste simulated?

**Comment by weihui1308** [comment]
> Hello, great work and i'm having a fun time implementing it.
> 
> main.py looks like a code to train the patch and optimize the best positions of the hotcold block. Is there a test code available?

see the val_patch.py
