### ISSUE TITLE
best.pt文件

### ISSUE THREAD

**Issue by wenfs** [weihui1308/HotCold_Block#6]
感谢作者在热红外图像上的对抗攻击工作！我是一名研一学生，对您的工作很感兴趣，正在复现代码。请问能否提供best.pt文件，以及能否提供论文中筛选出的1255张FLIR数据？

weights = "runs/train/exp/weights/best.pt"

期待您的回复，谢谢！

**Comment by weihui1308** [comment]
Sorry for the late reply.

You can download this checkpoint file at the following link:
https://drive.google.com/file/d/1gDL6baVFYgk_Lt9LPoZ0WXHQdVWU3kYy/view?usp=share_link

We have updated the readme. Please check it for more information.
