### ISSUE TITLE
Time Cost

### ISSUE THREAD

**Issue by wmrenr** [weihui1308/HotCold_Block#7]
Thank you for your great contribution
How long does it take you to implement such a physical attack in the real world?

**Comment by weihui1308** [comment]
Sorry for the late reply.

Do you mean the time to paste HotCold blocks on the human body?

**Comment by wmrenr** [comment]
> Sorry for the late reply.
> 
> Do you mean the time to paste HotCold blocks on the human body?

Right, can you give an approximate time cost?

**Comment by weihui1308** [comment]
According to my assessment, it takes about 20 minutes to prepare to launch an attack. The specific work includes making special shaped patches, pasting them to the corresponding positions, etc.
