### ISSUE TITLE
 the gbest_ Position and gbest_Value

### ISSUE THREAD

**Issue by wmrenr** [weihui1308/HotCold_Block#9]
I ran the code and got the following result, but I don't understand what does the gbest_ Position and gbest_Value mean?

gbest_position:  tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 0.]], device='cuda:0')
tensor([[0.55257, 0.28448],
        [0.01177, 0.31871],
        [0.32984, 0.35318],
        [0.30217, 0.14357]], device='cuda:0')
gbest_value:  0.24989676475524902

**Comment by weihui1308** [comment]
gbest_position contains the shape and position of the patch.
gbest_value implies the optimal value obtained by the PSO optimization algorithm. Please see line 135 in pso.py.
